# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgtecol', '0002_auto_20171117_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='mun_delimitacion',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Delimitaci\xf3n geografica', null=True, srid=4326, verbose_name='Delimitaci\xf3n'),
        ),
    ]
