# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgtecol', '0003_auto_20171117_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='mun_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
