# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaudalDiario',
            fields=[
                ('caudi_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('caudi_fecha_reporte', models.DateField(verbose_name='Fecha reporte')),
                ('caudi_caudal', models.FloatField(verbose_name='Caudal')),
                ('caudi_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('caudi_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Caudales diarios',
                'db_table': 'caudal_diario',
                'verbose_name': 'Caudal diario',
            },
        ),
    ]
