# -*- coding: utf-8 -*-
"""
Django settings for App project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os,sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(os.path.dirname(os.path.basename(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ')7vl$3fby#pdhe#@lj&xz5e*ir%i4&sv9g^_yj8f$5k^rwe#lr'

sys.path.append(os.path.join(os.path.join(BASE_DIR, ""), 'Aplications/'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Aplications.agua',
    'Aplications.usuarios',
    'Aplications.dashboard',
    'Aplications.estaciones',
    'Aplications.orgtecol',
    'Aplications.entidades',
    'Aplications.suelo',
    'Aplications.clima',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'App.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'resources')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'App.wsgi.application'



# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        #'NAME': 'bdpazet',
        'NAME': 'pazetbackup',
        #'NAME': 'pazet',
        #'USER': 'administrador',
        'USER': 'postgres',
        #'PASSWORD': 'devlocal',
        'PASSWORD': 'root',
        'HOST': 'localhost',
        'PORT': '5432',
        'OPTIONS': {
            'options': '-c search_path=public,general',
        },
    },
}

QGIS_TEMP = '/home/shamirtv/Documentos/'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]




# -------------------------------------------------------------------------------------------------
# ---------------------------------------- AUTENTICACIÓN ------------------------------------------
# -------------------------------------------------------------------------------------------------

from django.core.urlresolvers import reverse_lazy
#from django.urls import reverse_lazy


#http://apuntes-snicoper.readthedocs.io/es/latest/programacion/python/django/login_username_or_email.html
AUTH_AUTHENTICATION_TYPE = 'both' #both, email, username.
AUTHENTICATION_BACKENDS = (
'usuarios.backends.EmailOrUsernameModelBackend',
)

LOGIN_URL = reverse_lazy('auth:login')

LOGIN_REDIRECT_URL = reverse_lazy('dashboard:index')

LOGOUT_URL = reverse_lazy('auth:login')
SESSION_COOKIE_AGE = 40*60 #MINUTOS QUE DEMORA LA SESION ACTIVA

# -------------------------------------------------------------------------------------------------
# ---------------------------------------- FIN AUTENTICACIÓN --------------------------------------
# -------------------------------------------------------------------------------------------------


# -------------------------------------------------------------------------------------------------
# ------------------------------------ CONFIGURACIÓN DE LA CACHE ----------------------------------
# -------------------------------------------------------------------------------------------------

#CONFIGURACION PARA UTILIZAR MEMCACHED
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# -------------------------------------------------------------------------------------------------
# ------------------------------------ FIN CONFIGURACIÓN DE LA CACHE ----------------------------------
# -------------------------------------------------------------------------------------------------






# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/public/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'public'),
)
