# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClimaDiario',
            fields=[
                ('cdia_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cdia_fecha_reporte', models.DateField(verbose_name='Fecha reporte')),
                ('cdia_precipitacion', models.FloatField(blank=True, null=True, verbose_name='Precipitaci\xf3n')),
                ('cdia_temp_media', models.FloatField(blank=True, null=True, verbose_name='Temperatura Media')),
                ('cdia_temp_minima', models.FloatField(blank=True, null=True, verbose_name='Temperatura Minima')),
                ('cdia_temp_maxima', models.FloatField(blank=True, null=True, verbose_name='Temperatura Maxima')),
                ('cdia_humedad_relativa', models.FloatField(blank=True, null=True, verbose_name='Humedad relativa')),
                ('cdia_brillo_solar', models.FloatField(blank=True, null=True, verbose_name='Brillo solar')),
                ('cdia_evaporacion', models.FloatField(blank=True, null=True, verbose_name='Evaporaci\xf3n')),
                ('cdia_vel_viento', models.FloatField(blank=True, null=True, verbose_name='Velocidad viento')),
                ('cdia_calidad', models.SmallIntegerField(blank=True, null=True, verbose_name='Calidad')),
                ('cdia_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('cdia_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'managed': False,
                'verbose_name_plural': 'Clima diario',
                'db_table': 'clima_diario',
                'verbose_name': 'Clima diario',
            },
        ),
        migrations.CreateModel(
            name='ClimaMensual',
            fields=[
                ('cmen_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cmen_year', models.SmallIntegerField(verbose_name='A\xf1o')),
                ('cmen_month', models.SmallIntegerField(verbose_name='Mes')),
                ('cmen_precipitacion', models.FloatField(blank=True, null=True, verbose_name='Precipitaci\xf3n')),
                ('cmen_temp_media', models.FloatField(blank=True, null=True, verbose_name='Temperatura media')),
                ('cmen_temp_min', models.FloatField(blank=True, null=True, verbose_name='Temperatura minima')),
                ('cmen_temp_max', models.FloatField(blank=True, null=True, verbose_name='Temperatura maxima')),
                ('cmen_humedad_relativa', models.FloatField(blank=True, null=True, verbose_name='Humedad relativa')),
                ('cmen_brillo_solar', models.FloatField(blank=True, null=True, verbose_name='Brillo solar')),
                ('cmen_vel_viento', models.FloatField(blank=True, null=True, verbose_name='Velocidad viento')),
                ('cmen_evaporacion', models.FloatField(blank=True, null=True, verbose_name='Evaporaci\xf3n')),
                ('cmen_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('cmen_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'db_table': 'clima_mensual',
                'verbose_name': 'Clima mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClimaCo2',
            fields=[
                ('cotwo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cotwo_year', models.SmallIntegerField(verbose_name='A\xf1o')),
                ('cotwo_contenido', models.FloatField(verbose_name='Contenido de CO2')),
                ('cotwo_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('cotwo_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'CO2',
                'db_table': 'clima_co2',
                'managed': True,
                'verbose_name_plural': 'CO2s',
            },
        ),
        migrations.CreateModel(
            name='ClimaEscenariosCc',
            fields=[
                ('escc_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('escc_nombre', models.CharField(max_length=50, unique=True, verbose_name='Escenario')),
                ('escc_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('escc_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Escenario cambio climatico',
                'db_table': 'clima_escenarios_cc',
                'managed': True,
                'verbose_name_plural': 'Escenarios cambio climatico',
            },
        ),
        migrations.AddField(
            model_name='climaco2',
            name='escc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.ClimaEscenariosCc', verbose_name='Escenarios CC'),
        ),
    ]
