# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntdsEntidad',
            fields=[
                ('entds_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('entds_nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre entidad')),
                ('entds_siglas', models.CharField(max_length=10, unique=True, verbose_name='Siglas')),
                ('entds_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('entds_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Entidad',
                'db_table': 'entds_entidad',
                'managed': False,
                'verbose_name_plural': 'Entidades',
            },
        ),
    ]
