# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 23:42
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgtecol', '0004_auto_20171117_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('cul_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cul_nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Cultivo')),
                ('cul_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('cul_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Cultivo',
                'db_table': 'cultivo',
                'managed': True,
                'verbose_name_plural': 'Cultivos',
            },
        ),
        migrations.CreateModel(
            name='NivelFreatico',
            fields=[
                ('nivfre_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nivfre_nombre', models.CharField(max_length=50, unique=True, verbose_name='Tipo de Cultivo')),
                ('nivfre_coordenadas', django.contrib.gis.db.models.fields.PointField(help_text='Seleccione un punto de ubicaci\xf3n', srid=4326, verbose_name='Coordenadas Nivel Fre\xe1tico')),
                ('nivfre_altitud', models.IntegerField(verbose_name='Altitud')),
                ('nivfre_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('nivfre_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
                ('mun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgtecol.Municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Nivel Fre\xe1tico',
                'db_table': 'cul_nivel_freatico',
                'managed': True,
                'verbose_name_plural': 'Niveles Fre\xe1ticos',
            },
        ),
        migrations.CreateModel(
            name='TipoCultivo',
            fields=[
                ('tipcul_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipcul_nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Cultivo')),
                ('tipcul_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('tipcul_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
                ('cul_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo')),
            ],
            options={
                'verbose_name': 'Tipo de Cultivo',
                'db_table': 'cul_tipo_cultivo',
                'managed': True,
                'verbose_name_plural': 'Tipos de Cultivos',
            },
        ),
    ]
