# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='cul_tipo_cultivo',
            field=models.CharField(choices=[('Herb\xe1seos Frutas y Granos', 'Herb\xe1seos Frutas y Granos'), ('Herb\xe1seos Vegetales de Hoja', 'Herb\xe1seos Vegetales de Hoja'), ('Herb\xe1seos Raices y Tuberculos', 'Herb\xe1seos Raices y Tuberculos'), ('Herb\xe1seos Cultivos Forrajeros', 'Herb\xe1seos Cultivos Forrajeros'), ('Arb\xf3reos', 'Arb\xf3reos')], default='', max_length=100, verbose_name=''),
        ),
    ]
