# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aqfisioconserva',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='aqfisionoconser',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='tiporiego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.TipoRiego', verbose_name='Tipo de Riego'),
        ),
        migrations.AlterField(
            model_name='fechasiembra',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='nivelfreatico',
            name='mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgtecol.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='reqnutricion',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='tipocultivo',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='tiporiego',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
    ]
