# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgtecol', '0004_auto_20171117_0512'),
        ('cultivo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='municipio',
        ),
        migrations.AddField(
            model_name='cultivo',
            name='municipios',
            field=models.ManyToManyField(related_name='cultivos', through='cultivo.RegionCultivo', to='orgtecol.Municipio'),
        ),
        migrations.AlterField(
            model_name='regioncultivo',
            name='cul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioncultivo', to='cultivo.Cultivo', verbose_name='Cultivo'),
        ),
        migrations.AlterField(
            model_name='regioncultivo',
            name='mun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regioncultivo', to='orgtecol.Municipio', verbose_name='Municipio'),
        ),
    ]
