# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cultivo', '0002_auto_20180406_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='cul_nombre_bernaculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='cul_nombre_cientifico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cultivo'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='cul_variedad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cultivo'),
        ),
        migrations.AlterField(
            model_name='aqfisioconserva',
            name='aqfisioconser_wpnormal',
            field=models.FloatField(verbose_name='Productividad h\xeddrica ET0 y CO2'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='cul_nombre',
            field=models.CharField(max_length=50, verbose_name='Tipo de Cultivo'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_cew_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conductividad El\xe9ctrica'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_dia_n',
            field=models.CharField(max_length=200, verbose_name='D\xeda Riego'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_cew_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Conductividad El\xe9ctrica Riego'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_crit_lamina',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Criterio de L\xe1mina'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_crit_tiempo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Criterio de Tiempo'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_desdedia_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='D\xeda Criterio Riego'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_intervalo_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intervalo Criterio Riego'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_gen_lamina_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='L\xe1mina de Aplicaci\xf3n'),
        ),
        migrations.AlterField(
            model_name='eventoriego',
            name='eventoriego_lamina_n',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='L\xe1mina Aplicada'),
        ),
        migrations.AlterField(
            model_name='nivelfreatico',
            name='nivfre_altitud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altitud'),
        ),
        migrations.AlterField(
            model_name='nivelfreatico',
            name='nivfre_nombre',
            field=models.CharField(max_length=50, verbose_name='Tipo de Cultivo'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_drenaje_mod',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Clase de Drenaje Moderado'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_drenaje_opt',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Clase de Drenaje \xd3ptimo'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_drenaje_rest',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Clase de Drenaje Restrictivo'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_textura_mod',
            field=models.CharField(max_length=15, verbose_name='Textura Moderada'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_textura_opt',
            field=models.CharField(max_length=15, verbose_name='Textura \xd3ptima'),
        ),
        migrations.AlterField(
            model_name='reqfisico',
            name='reqfis_textura_rest',
            field=models.CharField(max_length=15, verbose_name='Textura Restringida'),
        ),
        migrations.AlterField(
            model_name='tiporiego',
            name='tiporiego_metodo',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Tipo Riego M\xe9todo'),
        ),
    ]
