# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-03 22:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstnCategoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('cat_nombre', models.CharField(max_length=50, unique=True, verbose_name='Categoria')),
                ('cat_siglas', models.CharField(max_length=50, unique=True, verbose_name='Siglas')),
                ('cat_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('cat_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Categoria',
                'db_table': 'estn_categoria',
                'managed': False,
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='EstnClase',
            fields=[
                ('clase_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('clase_nombre', models.CharField(max_length=50, unique=True, verbose_name='Clase')),
                ('clase_siglas', models.CharField(max_length=50, unique=True, verbose_name='Siglas')),
                ('clase_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('clase_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Clase',
                'db_table': 'estn_clase',
                'managed': False,
                'verbose_name_plural': 'Clases',
            },
        ),
        migrations.CreateModel(
            name='EstnEstacion',
            fields=[
                ('estn_codigo', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('estn_nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('estn_corriente', models.CharField(blank=True, max_length=200, null=True, verbose_name='Corriente')),
                ('estn_coordenadas', django.contrib.gis.db.models.fields.PointField(help_text='Seleccione un punto de ubicaci\xf3n', srid=4326, verbose_name='Coordenadas')),
                ('estn_estado', models.CharField(blank=True, choices=[('ACT', 'ACTIVO'), ('SUS', 'SUSPENDIDO')], default=None, max_length=10, null=True, verbose_name='Estado')),
                ('estn_altitud', models.FloatField(blank=True, null=True, verbose_name='Altitud')),
                ('estn_fecha_instalacion', models.DateField(blank=True, null=True, verbose_name='Fecha de instalaci\xf3n')),
                ('estn_fecha_suspension', models.DateField(blank=True, null=True, verbose_name='Fecha de suspensi\xf3n')),
                ('estn_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('estn_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Estaci\xf3n',
                'db_table': 'estn_estacion',
                'managed': False,
                'verbose_name_plural': 'Estaciones',
            },
        ),
        migrations.CreateModel(
            name='EstnTipo',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('tipo_nombre', models.CharField(max_length=1000, unique=True, verbose_name='Tipo')),
                ('tipo_siglas', models.CharField(max_length=100, unique=True, verbose_name='Siglas')),
                ('tipo_created', models.DateTimeField(auto_now_add=True, verbose_name='Registro')),
                ('tipo_updated', models.DateTimeField(auto_now=True, verbose_name='Actualizaci\xf3n')),
            ],
            options={
                'verbose_name': 'Tipo',
                'db_table': 'estn_tipo',
                'managed': False,
                'verbose_name_plural': 'Tipos',
            },
        ),
    ]
